name: Flutter CI

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
  pull_request:

env:
  APP_VERSION: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || '0.0.0' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.0
      
      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --split-per-abi --build-name=${{ env.APP_VERSION }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk-${{ github.ref_name }}
          path: ./build/app/outputs/flutter-apk/*.apk
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ./dist
      
      - name: Create Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: |
            ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}